### ISSUE TITLE
Couldn't I just as easily handle this as actions of a flux application?

### ISSUE THREAD

**Issue by ghost** [mbasso/react-wasm#5]
**General Information**
- [ ] Bug
- [ ] Improvement
- [ ] Feature
- [x ] Other: Chitchat

**Description**
I dig that you're sharing your interpretation and composition, is there any specific contextual reasoning that one wouldnt just stick their wasm in a projects flux actions, getting this as a composition agnostic abstraction?

(Add images if possible)
![image](https://user-images.githubusercontent.com/26851121/57005976-7a6e7500-6b91-11e9-8572-e0c610779631.png)

**Comment by ghost** [comment]
Also because this isnt an issue I'll close it, you probably got the email for an issue opened.

**Comment by mbasso** [comment]
Hi @etisdew,
thank you for opening this issue, I really like to discuss different implementations and ideas.
Do you mean why not using a global store with actions?
Yeah, I think that you can also instantiate a WebAssembly module using flux actions and putting it into the global store, It should work fine. However, I prefer to instantiate them locally (not always) for a couple of reasons.
Firstly, I'd like to put into the global state only data that cannot be put into the local one. Therefore, I usually ask myself "who is responsible to use manage, instantiate and use this module?". This library is react-focused so it has the advantage to provide you some facilities, you don't need to care about lifecycle methods and so on, you can just write your code in a declarative way.
After that, `WebAssembly.Module` and `WebAssembly.Instance` are not serializable. In a flux architecture we should have serializable actions and state in order to persist, reproduce and rehydrate the contents of the store. In addition, it is impossible to perform time-travel debugging.
About this library, I think that we might not be able to provide a generic API because of the bunch of different libraries out here that implement flux mechanism.
In certain cases using flux might be convenient for sure, it only depends on your system, I'm not saying that this library is perfect for everyone and for every use case. For this reason I'm open to discuss new implementations, API and so on 😄

P.S. The image is awesome 😆
